apiVersion: v1
kind: Service
metadata:
  name: nps-pension
spec:
  externalIPs:
  - 192.168.100.210
  ports:
  - port: 9100
    targetPort: 9000
  selector:
    app: nps-pension
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nps-pension-deployment
  labels:
    app: nps-pension
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nps-pension
  template:
    metadata:
      labels:
        app: nps-pension
    spec:
      containers:
      - name: nps-pension
        image: nps-pension:0.1
        volumeMounts:
        - name: files-volume
          mountPath: /data/twinreader
      volumes:
      - name: files-volume
        hostPath:
          path: /data/twinreader
          type: Directory
